import pandas as pd
import os
import json
import glob
from sklearn.metrics import accuracy_score, f1_score

# 1. Get the GitHub Username of the person who made the Pull Request
group_name = os.environ.get("GROUP_NAME", "Unknown Student")

# 2. Load the Secret Answer Key (Generated by GitHub Actions)
truth_file = "grader/test_labels.csv"
if not os.path.exists(truth_file):
    print("❌ Error: Secret labels not found. Contact Instructor.")
    exit(1)
truth_df = pd.read_csv(truth_file)

# 3. Find the student's submission.csv file
sub_files = glob.glob("submission/*.csv")
if not sub_files:
    print("❌ Error: No CSV file found in the submission folder.")
    exit(1)

sub_df = pd.read_csv(sub_files[0])

# 4. Compare and Grade!
try:
    # Ensure both dataframes are sorted so rows match up perfectly
    truth_df = truth_df.sort_values("id")
    sub_df = sub_df.sort_values("id")

    if len(truth_df) != len(sub_df):
        print(f"❌ Error: Row count mismatch. Expected {len(truth_df)}, got {len(sub_df)}")
        exit(1)

    # Calculate Accuracy and F1 Score (Standard for Binary Classification)
    acc = accuracy_score(truth_df['result'], sub_df['result'])
    f1 = f1_score(truth_df['result'], sub_df['result'], zero_division=0)

    print(f"✅ Grading Successful!")
    print(f"Accuracy: {acc:.4f}")
    print(f"F1 Score: {f1:.4f}")

    # 5. Save the result so the GitHub Action can update the Leaderboard
    os.makedirs("leaderboard_data", exist_ok=True)
    result_data = {
        "group": group_name,
        "f1_score": round(f1, 4),
        "accuracy": round(acc, 4)
    }

    with open("leaderboard_data/result.json", "w") as f:
        json.dump(result_data, f)

except Exception as e:
    print(f"❌ Error during grading: {e}")
    exit(1)
